name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  unit-tests:
    name: Unit tests (Python 3.12)
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install project
        run: |
          python -m pip install --upgrade pip
          pip install -e .

      - name: Run unit tests
        run: |
          python -m unittest discover -s tests -p "test_*.py" -v

  build-package:
    name: Build distribution artifacts
    runs-on: ubuntu-latest
    needs: unit-tests

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package
        run: |
          python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: pinybytecnn-dist
          path: dist/
          if-no-files-found: error
